# Generated by Django 6.0 on 2025-12-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="full_name",
        ),
        migrations.AlterField(
            model_name="workout",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="gym.trainerprofile",
            ),
        ),
    ]
